# Project Information
site_name: Finanza Coatta
site_url:  https://github.com/AntonioBerna/finanza-coatta
site_author: Antonio Bernardini
site_description: Finanza Coatta è la prima roadmap in dialetto romano che te porta passo passo dentro er mondo della finanza. Da principiante che nun sa 'na mazza 🤯 a esperto che fa' mosse da vero coatto 🏦🔥.

# Repository
repo_name: AntonioBerna/finanza-coatta
repo_url: https://github.com/AntonioBerna/finanza-coatta

# Copyright
copyright: Copyright &copy; 2025 Antonio Bernardini

# Configuration
theme:
  name: material
  language: it
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto 
    code: JetBrains Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - mkdocs_quiz
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AntonioBerna
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/berna_engineer

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extras
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Base:
    - Indice coatto: base/indice-coatto.md
    - Impara a Risparmià:
      - "'Na panoramica pe' capisse": base/impara-a-risparmia/na-panoramica-pe-capisse.md
      - Er budget: base/impara-a-risparmia/er-budget.md
      - "Strategie pe' risparmià": base/impara-a-risparmia/strategie-pe-risparmia.md
      - Routine de conti: base/impara-a-risparmia/routine-de-conti.md
      - Pensa a quanno vai in pensione: base/impara-a-risparmia/pensa-a-quanno-vai-in-pensione.md
    - Risparmia sul mutuo:
      - work-in-progress.md
    - Fai il tuo primo investimento:
      - work-in-progress.md
    - Investi in azioni:
      - work-in-progress.md
    - Investimenti sostenibili:
      - work-in-progress.md
    - Il Mercato Obbligazionario:
      - work-in-progress.md
  - Intermedio:
    - Indice coatto: intermedio/indice-coatto.md
    - Paga meno tasse (legalmente):
      - work-in-progress.md
  - Avanzato:
    - Indice coatto: avanzato/indice-coatto.md
    - work-in-progress.md
